version: "3.9"
services:
  nextjs:
    build: ./frontend
    ports:
      - 3000:3000
  nginx:
    build: ./frontend/nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
      - 3001:3001
      - 443:443
    volumes:
      - ./enviroment/certs/syrpinboris.crt:/etc/ssl/syrpinboris.crt
      - ./enviroment/certs/syrpinboris.key:/etc/ssl/syrpinboris.key
  strapi:
    build: ./strapi
    ports:
      - 1337:1337
